### ISSUE TITLE
Landing point highlight

### ISSUE THREAD

**Issue by znichola** [znichola/red-tetris#40]
I like the idea of this effect, and I think it could actually be really cool for the invisible pile gamemode, we could just display, the highlight of the landing spot.

**Comment by znichola** [comment]
```css
.landing {
  box-shadow: 0 -1.5px 0 0 var(--dark);
}
```

some css to add a line above the cell, it's a shadow so it does not change the div dimensions.
